{
 "title": "Django App Stats",
 "description": "Dashboard with host machine and HTTP server metrics.",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU time spent / mode",
   "type": "timeseries",
   "description": "Average CPU time spent in each mode. Values sum up to 1 for each sampling.",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "avg by(mode, instance) (irate(node_cpu_seconds_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Load (%)",
   "type": "timeseries",
   "description": "Average CPU load % (i.e. time spent not in \"idle\" mode)",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{job=\"host_machine\", mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mem % used",
   "type": "gauge",
   "description": "Current memory % used. \"Used\" memory is defined as:\ntotal_mem - free_mem - cache_mem - buff_mem",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "  (\n      (\n          node_memory_MemTotal_bytes\n        -\n          (node_memory_MemFree_bytes + node_memory_Cached_bytes + node_memory_Buffers_bytes)\n      )\n    /\n      node_memory_MemTotal_bytes\n  )\n*\n  100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory available (GB)",
   "type": "gauge",
   "description": "Current available memory (GB). \"Available\" memory is defined as memory which can be allocated immediately.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes / 1000000000",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Django", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "HTTP Request Latency per View (sec)",
   "type": "timeseries",
   "description": "Average rate of request latency, grouped by Django view method called",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(view, ) (rate(django_http_requests_latency_seconds_by_view_method_sum[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP 95%tile Request Latency per view/method",
   "type": "timeseries",
   "description": "95%tile request latency measured by view/method",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(view, method, le) (rate(django_http_requests_latency_seconds_by_view_method_bucket[5m])))",
     "legendFormat": "{{view}} - {{method}}"
    }
   ]
  },
  {
   "title": "HTTP 500 by View",
   "type": "timeseries",
   "description": "Rate of HTTP 500 responses per Django view",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "django_app_http_500_responses_by_view:rate5m",
     "legendFormat": "{{view}}"
    }
   ]
  }
 ]
}