groups:
- name: node-exporter
  rules:
  # Available ext4 fs space (in GB)
  - record: node_host_available_fs_space_ext4
    expr: node_filesystem_avail_bytes{fstype="ext4"} / (1024*1024*1024)
  # The average network traffic received, per second, over the last minute (in bytes)
  - record: node_host_network_recv_bytes_over_last_min
    expr: rate(node_network_receive_bytes_total[1m])

  # Alerts
  - alert: CPU usage > 80% (1 min)
    expr: 100 - avg by (instance) (irate(node_cpu_seconds_total{mode="idle"}[1m])) * 100 > 80
    for: 1m
    labels:
      severity: "high"
      alerttype: "server"
    annotations:
      summary: "High CPU usage"
      description: "Server CPU usage exceeds 80% for more than 1 minute."

  - alert: CPU usage > 80% (10 min)
    expr: 100 - avg by (instance) (irate(node_cpu_seconds_total{mode="idle"}[1m])) * 100 > 80
    for: 10m
    labels:
      severity: "critical"
      alerttype: "server"
    annotations:
      summary: "Critically high CPU usage"
      description: "Server CPU usage exceeds 80% for more than 10 minutes."
